### ISSUE TITLE
Questions for expense edit flow

### ISSUE THREAD

**Issue by LucasGinard** [gastsail/expenses-KMP#2]
Buenas Gaston.

Hago este issue para ir definiendo el flujo de editar si te parece?.

1 - consulta el tema del generado del ID podría hacerlo de esta manera?:

```  kotlin:
data class Expense(
    val id:Int = generateId(),
    val amount: Double,
    val category: ExpenseCategory,
    val description: String
) {
    val icon = category.icon
    companion object {
        private var counter = 0

        private fun generateId(): Int {
            counter++
            return counter
        }
    }
}
```
2 - Consulta para ir a la pantalla de editar seria con un boton o dandole simplemente al card ?, voy haciendo dandole al cardcito por mientras si te parece ?

**Comment by gastsail** [comment]
Hola Lucas, la idea seria solo incluir un Long de id e incluirlo a cada elemento de la lista, voy a actualizarte el modelo y los datos para que arranques por ahi

**Comment by gastsail** [comment]
En este commit https://github.com/gastsail/expenses-KMP/commit/77330fb47ba96047acc189117a164568650c537f vas a poder ver los cambios agregados, ahora cuando agregas un nuevo item a la lista se agrega con su correspondiente id , te hice dos TODO's los cuales debes seguir para hacerlo andar.

Primero cuando clicas un elemento de la lista debes mediante argumentos mandar esa expensa a la pantalla `AddExpenseScreen`, luego si los datos son validos completar los 3 datos y la opción de add expense (nombre del boton) cambiarlo por edit expense.

Recordá que para editar la expense vas a tener que usar el metodo editExpense el cual agregue en este commit junto a sus metodos en el repo.

https://github.com/gastsail/expenses-KMP/commit/50a10e3b58f3f25eb9afe27e749b900c20857be5

**Comment by LucasGinard** [comment]
#3 Entendido graciass, este seria el Pull 👍🏽
